language: node_js
sudo: false
node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"
script:
  - npm run coverage
after_success:
  - npm run publish-coverage
services:
  - rabbitmq
  - redis-server
env:
  - MONGODB_VERSION="3.2.5"
  - MONGODB_VERSION="3.0.11"
  - MONGODB_VERSION="2.6.12"
before_install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - tar xfz mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - export PATH=`pwd`/mongodb-linux-x86_64-$MONGODB_VERSION/bin:$PATH
  - mkdir -p data/db
  - mongod --dbpath=data/db > /dev/null &
  - sleep 5
